### ISSUE TITLE
"export 'default' (imported as 'Worker') was not found in './transcode.worker.js' 

### ISSUE THREAD

**Issue by DoracisMu** [Ma-Tao007/xunfei-vioceAl-vueSDK#1]
我按照您的源码放入自己的项目，npm run dev时提示如上错误，请问是怎么一回事呢？ 然后我看到transcode.worker.js没有export xxx，请问是我还缺配置什么东西吗？

**Comment by Ma-Tao007** [comment]
稍等   我复现下看看

**Comment by Ma-Tao007** [comment]
稍等   我复现下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;muuujian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月25日(星期五) 下午2:44
收件人:&nbsp;&quot;Ma-Tao007/xunfei-vioceAl-vueSDK&quot;<xunfei-vioceAl-vueSDK@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ma-Tao007/xunfei-vioceAl-vueSDK] &quot;export &#39;default&#39; (imported as &#39;Worker&#39;) was not found in &#39;./transcode.worker.js&#39;  (#1)

**Comment by DoracisMu** [comment]
> 稍等 我复现下------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;muuujian&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年12月25日(星期五) 下午2:44 收件人:&nbsp;&quot;Ma-Tao007/xunfei-vioceAl-vueSDK&quot;<xunfei-vioceAl-vueSDK@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Ma-Tao007/xunfei-vioceAl-vueSDK] &quot;export &#39;default&#39; (imported as &#39;Worker&#39;) was not found in &#39;./transcode.worker.js&#39; (#1)

谢谢您的帮助，万分感谢，这是我的项目截图
![image](https://user-images.githubusercontent.com/29179299/103123951-fac7df00-46c0-11eb-90c1-024f7fd96a96.png)

**Comment by Ma-Tao007** [comment]
的

**Comment by Ma-Tao007** [comment]
我刚刚复现了代码   我vue使用的是2.5.2版本   你是不是vue版本有问题    还有你截图我看不到   这个github图片服务器挂掉了吧

**Comment by Ma-Tao007** [comment]
我自己使用npm run dev运行出错了   使用了yarn run serve运行的   打包都行    没有出现你说的错误    可以直接运行 并测试成功

**Comment by Ma-Tao007** [comment]
你看下你的Vue版本   或者使用yarn  run serve运行试试------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;muuujian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月25日(星期五) 下午2:54
收件人:&nbsp;&quot;Ma-Tao007/xunfei-vioceAl-vueSDK&quot;<xunfei-vioceAl-vueSDK@noreply.github.com&gt;;
抄送:&nbsp;&quot;Ma-Tao007&quot;<2568819232@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Ma-Tao007/xunfei-vioceAl-vueSDK] &quot;export &#39;default&#39; (imported as &#39;Worker&#39;) was not found in &#39;./transcode.worker.js&#39;  (#1)

**Comment by DoracisMu** [comment]
老哥谢谢你的提醒，我再次检查了一下，然后又搜索了npm i worker发现我少了一步，在webpack.base.conf上要配置以worker结尾的解析方法，加上了这个就OK了，怪我太菜哈哈，也谢谢老哥指点
