### ISSUE TITLE
worker这个错怎么解决，一直找不到办法

### ISSUE THREAD

**Issue by lyStray** [Ma-Tao007/xunfei-vioceAl-vueSDK#3]
transcode.worker.worker.js:1 Uncaught SyntaxError: Unexpected token '<'
![image](https://user-images.githubusercontent.com/49094810/118947783-4047ba00-b98a-11eb-96d0-436e176490c8.png)
![image](https://user-images.githubusercontent.com/49094810/118947794-4473d780-b98a-11eb-8b86-e49518af2c70.png)

**Comment by Ma-Tao007** [comment]
已经解决了是吗
